package pooky;




import java.awt.Color;
import java.awt.Container;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import static pooky.Language.Languages;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pooja2307
 */
public class translate extends javax.swing.JFrame {

private Container c;
 
    public static HashMap<String,String> languagesHashMap=new HashMap<>();
public TranslateService ts=new TranslateService();
String newKey;
String lang1;
String lang2;
String langb1;
String langb2;
int lCounter=0;
int rCounter=0;

    public translate() {
        c=getContentPane();
            c.setLayout(null);
            c.setBackground(Color.WHITE);
            initComponents();
        populateHashMap();
   //      Iterator it = languagesHashMap.keySet().iterator();
//while(it.hasNext())
//{
//    jComboBox1.addItem(it);
//}
       
        Set s=languagesHashMap.keySet();
    String[] s1= (String[]) s.toArray(new String[s.size()]);
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(s1));
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(s1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        u1Text = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        u2Text = new javax.swing.JTextArea();
        translate2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        translate3 = new javax.swing.JButton();
        translate4 = new javax.swing.JButton();
        translate5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        history1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setEditable(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Language", "Afrikaans", "Albanian", "Arabic ", "Azerbaijani ", "Basque", "Bengali", "Belarusian", "Bulgarian", "Catalan", "ChineseSimplified", "ChineseTraditional ", "Croatian", "Czech", "Danish", "Dutch ", "English ", "Esperanto", "Estonian", "Filipino", "Finnish", "French ", "Galician", "Georgian", "German ", "Greek ", "Gujarati", "HaitianCreole", "Hebrew", "Hindi ", "Hungarian ", "Icelandic ", "Indonesian", "Irish", "Italian ", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak ", "Slovenian;", "Spanish ", "Swahili ", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        u1Text.setColumns(20);
        u1Text.setRows(5);
        jScrollPane1.setViewportView(u1Text);

        u2Text.setColumns(20);
        u2Text.setRows(5);
        jScrollPane2.setViewportView(u2Text);

        translate2.setBackground(new java.awt.Color(153, 255, 255));
        translate2.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        translate2.setForeground(new java.awt.Color(0, 0, 102));
        translate2.setText("Translate");
        translate2.setOpaque(false);
        translate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translate2ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("AR CENA", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("My Language");
        jLabel2.setOpaque(true);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pooky/images.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Bernard MT Condensed", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Directions Translator");
        jLabel4.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Orator Std", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("History");
        jLabel1.setOpaque(true);

        button1.setActionCommand("Complete");
        button1.setBackground(new java.awt.Color(153, 255, 255));
        button1.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(0, 0, 102));
        button1.setLabel("Finish - Go to the Survey!");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        translate3.setBackground(new java.awt.Color(153, 255, 255));
        translate3.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        translate3.setForeground(new java.awt.Color(0, 0, 102));
        translate3.setText("Translate");
        translate3.setOpaque(false);
        translate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translate3ActionPerformed(evt);
            }
        });

        translate4.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 18)); // NOI18N
        translate4.setForeground(new java.awt.Color(0, 0, 102));
        translate4.setText("Error in Translating?");
        translate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translate4ActionPerformed(evt);
            }
        });

        translate5.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 18)); // NOI18N
        translate5.setForeground(new java.awt.Color(0, 0, 102));
        translate5.setText("Error in Translating?");
        translate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translate5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        label18.setAlignment(java.awt.Label.CENTER);
        label18.setBackground(new java.awt.Color(153, 255, 255));
        label18.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        label18.setForeground(new java.awt.Color(0, 0, 102));
        label18.setText("User 2");

        label19.setAlignment(java.awt.Label.CENTER);
        label19.setBackground(new java.awt.Color(153, 255, 255));
        label19.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        label19.setForeground(new java.awt.Color(0, 0, 102));
        label19.setText("User 1");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pooky/Thought_Bubble_Comics.png"))); // NOI18N
        jLabel9.setText("jLabel8");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pooky/Thought_Bubble_Comics.png"))); // NOI18N
        jLabel10.setText("jLabel8");

        history1.setColumns(20);
        history1.setRows(5);
        jScrollPane3.setViewportView(history1);

        jLabel6.setBackground(new java.awt.Color(153, 255, 255));
        jLabel6.setFont(new java.awt.Font("Orator Std", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("History");
        jLabel6.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(153, 255, 255));
        jLabel8.setFont(new java.awt.Font("Orator Std", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Frequent Searches");
        jLabel8.setOpaque(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pooky/arrows-146085_640 - Copy - Copy.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pooky/arrows-146085_640 - Copy - Copy - Copy.png"))); // NOI18N
        jButton2.setHideActionText(true);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pooky/arrows-146085_640 - Copy.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pooky/arrows-146085_640.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(translate5))
                        .addGap(141, 141, 141)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(translate4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(translate3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222)
                .addComponent(translate2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1256, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(translate3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(translate2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(translate5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(translate4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(528, Short.MAX_VALUE)))
        );

        button1.getAccessibleContext().setAccessibleName("Complete ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void translate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translate2ActionPerformed
        
                
        String text1 = u2Text.getText();
        
        try {
            String text2;
           if(lang1.equals(lang2))
            {
                u1Text.setText(u2Text.getText());
                text2=text1;
            }
           else {
            text2 = ts.translate(text1, languagesHashMap.get(lang1), languagesHashMap.get(lang2));
           u1Text.setText(text2);
          
           }
           String history= history1.getText();
          
          history1.setText(history+"\n"+text1+ "-"+text2);
          
        } catch (IOException ex) {
            Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_translate2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String s2=null;
        String s4=null;
        String s6=null;
        String s8=null;
        
        lang1 = jComboBox1.getSelectedItem().toString();
         String s1= "User 1";
        String s3= "Translate";
        String s5= "Error in translating?";
        String s7= jLabel5.getText();
    try {
        s2= ts.translate(s1, languagesHashMap.get(lang1), Language.English );
        s4= ts.translate(s3, languagesHashMap.get(lang1), Language.English );
        s6= ts.translate(s5, languagesHashMap.get(lang1), Language.English );
        s8= ts.translate(s7, languagesHashMap.get(lang1), languagesHashMap.get(langb1) );} 
    catch (IOException ex) {
        Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
    }
        label19.setText(s2);
        translate3.setText(s4);
        translate5.setText(s6);
        jLabel5.setText(s8);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    String s2=null;
        String s4=null;
        String s6=null;
        String s8=null;
        
        lang2= jComboBox2.getSelectedItem().toString();
    String s1= "User 2";
        String s3= "Translate";
        String s5= "Error in translating?";
        String s7= jLabel7.getText();
    try {
        s2= ts.translate(s1, languagesHashMap.get(lang1), Language.English );
        s4= ts.translate(s3, languagesHashMap.get(lang1), Language.English );
        s6= ts.translate(s5, languagesHashMap.get(lang1), Language.English );
        s8= ts.translate(s7, languagesHashMap.get(lang2), languagesHashMap.get(langb2) );
    } catch (IOException ex) {
        Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
    }
        label18.setText(s2);
        translate2.setText(s4);
        translate4.setText(s6);
        jLabel7.setText(s8);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

try {
   //Set your page url in this string.
         String url = "https://ufl.qualtrics.com/SE/?SID=SV_8ukSxUlo0r4BG7P";
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_button1ActionPerformed

    private void translate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translate3ActionPerformed
 String text1 = u1Text.getText();
        String text2 = null;
        try {
            if(lang1.equals(lang2))
            {
                u2Text.setText(u1Text.getText());
                text2=text1;
            }
            else{
                
            text2 = ts.translate(text1, languagesHashMap.get(lang2), languagesHashMap.get(lang1));
           u2Text.setText(text2);
          
            }
            
           String history= history1.getText();
          
          history1.setText(history+"\n"+text1+ "-"+text2);
          
        } catch (IOException ex) {
            Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_translate3ActionPerformed

    private void translate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translate4ActionPerformed
rCounter++;
    
        jLabel7.setText("Count:"+rCounter);
    }//GEN-LAST:event_translate4ActionPerformed

    private void translate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translate5ActionPerformed
        lCounter++;
    
        jLabel5.setText("Count:"+lCounter);
    }//GEN-LAST:event_translate5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String s1 ="Go Right";
      String s3 ="Go Right";
      String s2="Go Right";
    try {
       if(jComboBox1.getSelectedItem().toString()!= "English"){
       s1 = ts.translate(s2, languagesHashMap.get(jComboBox1.getSelectedItem().toString()), Language.English);}
       if(jComboBox2.getSelectedItem().toString()!= "English"){ 
       s3 = ts.translate(s2, languagesHashMap.get(jComboBox2.getSelectedItem().toString()), Language.English);}
       u1Text.setText(s1);
       u2Text.setText(s3);
       
    } catch (IOException ex) {
        Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
    }
     String history= history1.getText();
          
          history1.setText(history+"\n"+s1+ "-"+s3);
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      String s1 = null;
      String s3 = null;
      String s2="Right";
    try {
        s1 = ts.translate(s2, languagesHashMap.get(lang1), Language.English);
        s3 = ts.translate(s2, languagesHashMap.get(lang2), Language.English);
    } catch (IOException ex) {
        Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
    }
        u1Text.setText(s1);
        u2Text.setText(s3);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String s1 ="Go Ahead";
      String s3 ="Go Ahead";
      String s2="Go Ahead";
    try {
       if(jComboBox1.getSelectedItem().toString()!= "English"){
       s1 = ts.translate(s2, languagesHashMap.get(jComboBox1.getSelectedItem().toString()), Language.English);}
       if(jComboBox2.getSelectedItem().toString()!= "English"){ 
       s3 = ts.translate(s2, languagesHashMap.get(jComboBox2.getSelectedItem().toString()), Language.English);}
       u1Text.setText(s1);
       u2Text.setText(s3);
       
    } catch (IOException ex) {
        Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
    }
    String history= history1.getText();
          
          history1.setText(history+"\n"+s1+ "-"+s3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  String s1 ="Go Ahead";
      String s3 ="Go Ahead";
      String s2="Go Ahead";
    try {
       if(jComboBox1.getSelectedItem().toString()!= "English"){
       s1 = ts.translate(s2, languagesHashMap.get(jComboBox1.getSelectedItem().toString()), Language.English);}
       if(jComboBox2.getSelectedItem().toString()!= "English"){ 
       s3 = ts.translate(s2, languagesHashMap.get(jComboBox2.getSelectedItem().toString()), Language.English);}
       u1Text.setText(s1);
       u2Text.setText(s3);
       
    } catch (IOException ex) {
        Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String s1 ="Go Down";
      String s3 ="Go Down";
      String s2="Go Down";
    try {
       if(jComboBox1.getSelectedItem().toString()!= "English"){
       s1 = ts.translate(s2, languagesHashMap.get(jComboBox1.getSelectedItem().toString()), Language.English);}
       if(jComboBox2.getSelectedItem().toString()!= "English"){ 
       s3 = ts.translate(s2, languagesHashMap.get(jComboBox2.getSelectedItem().toString()), Language.English);}
       u1Text.setText(s1);
       u2Text.setText(s3);
       
    } catch (IOException ex) {
        Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
    }
    String history= history1.getText();
          
          history1.setText(history+"\n"+s1+ "-"+s3);
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String s1 ="Go Left";
      String s3 ="Go Left";
      String s2="Go Left";
    try {
       if(jComboBox1.getSelectedItem().toString()!= "English"){
       s1 = ts.translate(s2, languagesHashMap.get(jComboBox1.getSelectedItem().toString()), Language.English);}
       if(jComboBox2.getSelectedItem().toString()!= "English"){ 
       s3 = ts.translate(s2, languagesHashMap.get(jComboBox2.getSelectedItem().toString()), Language.English);}
       u1Text.setText(s1);
       u2Text.setText(s3);
       
    } catch (IOException ex) {
        Logger.getLogger(translate.class.getName()).log(Level.SEVERE, null, ex);
    }
    String history= history1.getText();
          
          history1.setText(history+"\n"+s1+ "-"+s3);
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(translate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(translate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(translate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(translate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              translate t= new translate();
    t.langb1 = t.jComboBox1.getSelectedItem().toString();
    t.langb2 = t.jComboBox2.getSelectedItem().toString();
                new translate().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JTextArea history1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private javax.swing.JButton translate2;
    private javax.swing.JButton translate3;
    private javax.swing.JButton translate4;
    private javax.swing.JButton translate5;
    private javax.swing.JTextArea u1Text;
    private javax.swing.JTextArea u2Text;
    // End of variables declaration//GEN-END:variables
private void populateHashMap() {
languagesHashMap.put("English", "en");
for (String key:Languages.keySet()){
try{

newKey=ts.translate(key, Languages.get(key), Language.English);
languagesHashMap.put(newKey, Languages.get(key));

}
catch(Exception e){
System.out.println(key);
}
}
languagesHashMap.remove("ChineseSimplified");
languagesHashMap.remove("ChineseTraditional");
languagesHashMap.put("中国",Language.ChineseSimplified);
languagesHashMap.put("中國",Language.ChineseTraditional);

}
}

